//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not enough right for modify the registry key. Please login as administrator or power user and try again..
        /// </summary>
        internal static string ADMINISATATOR_NEEDED {
            get {
                return ResourceManager.GetString("ADMINISATATOR_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /reszletes\tShow detailed error description.
        /// </summary>
        internal static string ARG_HELP_DETAILED {
            get {
                return ResourceManager.GetString("ARG_HELP_DETAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\tShow Help.
        /// </summary>
        internal static string ARG_HELP_HELP {
            get {
                return ResourceManager.GetString("ARG_HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SQL:{Measurement Id}\tLoad from SQL database.
        /// </summary>
        internal static string ARG_HELP_SQL {
            get {
                return ResourceManager.GetString("ARG_HELP_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SQL_Load:{Measurement Id}\tLoad from SQL database./n/SQL_Continue:{Measurement Id}\tContinue a SQL stored measure..
        /// </summary>
        internal static string ARG_HELP_SQL_CONTINUABLE {
            get {
                return ResourceManager.GetString("ARG_HELP_SQL_CONTINUABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tesztDB\tUsing Test database. (or condition with  &apos;DBUseRelease&apos; user-level XML config parameter..
        /// </summary>
        internal static string ARG_HELP_TEST_DB {
            get {
                return ResourceManager.GetString("ARG_HELP_TEST_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Measurement.
        /// </summary>
        internal static string CANCEL_MEASURE {
            get {
                return ResourceManager.GetString("CANCEL_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above limit.
        /// </summary>
        internal static string CHECKEDVALUE_ABOVE_LIMIT {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_ABOVE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Limit.
        /// </summary>
        internal static string CHECKEDVALUE_BELOW_LIMIT {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_BELOW_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: {0}, Limits: {1}..{2}, Result: {3}.
        /// </summary>
        internal static string CHECKEDVALUE_TOSTRING {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within the limits.
        /// </summary>
        internal static string CHECKEDVALUE_WITHIN_LIMIT {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_WITHIN_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        internal static string CHECKING {
            get {
                return ResourceManager.GetString("CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the measurement?.
        /// </summary>
        internal static string ConsoleApplication_CancelQuestion {
            get {
                return ResourceManager.GetString("ConsoleApplication_CancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Canceled.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndCanceled {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------Error Summary -------------.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndErrorSummary {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement result: Failed.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndFailed {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement: Passed.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndOk {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to exit..
        /// </summary>
        internal static string ConsoleApplication_ToExit {
            get {
                return ResourceManager.GetString("ConsoleApplication_ToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to exit. {1}.
        /// </summary>
        internal static string ConsoleApplication_ToExitWithParam {
            get {
                return ResourceManager.GetString("ConsoleApplication_ToExitWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracefile has been saved into {0} directory..
        /// </summary>
        internal static string ConsoleApplication_TracefileSavedInfo {
            get {
                return ResourceManager.GetString("ConsoleApplication_TracefileSavedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key.
        /// </summary>
        internal static string ConsoleHelper_PressAnyKey {
            get {
                return ResourceManager.GetString("ConsoleHelper_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DIALOG_RESULT_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DIALOG_RESULT_NO {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DIALOG_RESULT_OK {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retr.
        /// </summary>
        internal static string DIALOG_RESULT_RETRY {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DIALOG_RESULT_YES {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use double-click to select..
        /// </summary>
        internal static string DOUBLE_CLICK_TO_SELECT {
            get {
                return ResourceManager.GetString("DOUBLE_CLICK_TO_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened.
        /// </summary>
        internal static string ERROR_HAPPEND {
            get {
                return ResourceManager.GetString("ERROR_HAPPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened: &apos;{0}&apos;.
        /// </summary>
        internal static string ERROR_HAPPEND_PARAM {
            get {
                return ResourceManager.GetString("ERROR_HAPPEND_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal lenght are {0} characters..
        /// </summary>
        internal static string ERROR_MIN_LENGHT {
            get {
                return ResourceManager.GetString("ERROR_MIN_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value has not been found for &apos;{0}&apos;..
        /// </summary>
        internal static string EXCEPTION_SQL_NO_DATA_FOR {
            get {
                return ResourceManager.GetString("EXCEPTION_SQL_NO_DATA_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value has not been found for &apos;{0}&apos; at {1} the last {2} hours..
        /// </summary>
        internal static string EXCEPTION_SQL_NO_DATA_FOR_WITHIN_HOURS {
            get {
                return ResourceManager.GetString("EXCEPTION_SQL_NO_DATA_FOR_WITHIN_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested SQL record is not existing in table {0}. {1}.
        /// </summary>
        internal static string EXCEPTION_SQL_NO_ROW_AT_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_SQL_NO_ROW_AT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain full username of user &apos;{0}&apos; from LDAP..
        /// </summary>
        internal static string LDAP_ERROR {
            get {
                return ResourceManager.GetString("LDAP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided SqlId is not found at the table..
        /// </summary>
        internal static string LOAD_MEASURE_SELECT_FORM_ERROR_INFO_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOAD_MEASURE_SELECT_FORM_ERROR_INFO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided SqlId is not a number..
        /// </summary>
        internal static string LOAD_MEASURE_SELECT_FORM_ERROR_INFO_NOT_NUMBER {
            get {
                return ResourceManager.GetString("LOAD_MEASURE_SELECT_FORM_ERROR_INFO_NOT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection be doubleclick at table or manual here:.
        /// </summary>
        internal static string LOAD_MEASURE_SELECT_FORM_INFO {
            get {
                return ResourceManager.GetString("LOAD_MEASURE_SELECT_FORM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement is already saved (same S/N and measure date)..
        /// </summary>
        internal static string MEASURE_ALREADY_SAVED_ERROR {
            get {
                return ResourceManager.GetString("MEASURE_ALREADY_SAVED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string MEASURE_FAILED {
            get {
                return ResourceManager.GetString("MEASURE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement (ID: {0}) has been loaded. S/N is &apos;{1}&apos;. Date: {2}..
        /// </summary>
        internal static string MEASURE_LOADED {
            get {
                return ResourceManager.GetString("MEASURE_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement has been saved. ID: {0}.
        /// </summary>
        internal static string MEASURE_SAVED {
            get {
                return ResourceManager.GetString("MEASURE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string MEASURE_SUCCESSFULL {
            get {
                return ResourceManager.GetString("MEASURE_SUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring.
        /// </summary>
        internal static string MEASURING {
            get {
                return ResourceManager.GetString("MEASURING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Existing.
        /// </summary>
        internal static string NOT_EXIST {
            get {
                return ResourceManager.GetString("NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Initialized.
        /// </summary>
        internal static string NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has not to be set.
        /// </summary>
        internal static string NOT_SET {
            get {
                return ResourceManager.GetString("NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} param to continue..
        /// </summary>
        internal static string PARAM_TO_CONTINUE {
            get {
                return ResourceManager.GetString("PARAM_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite..
        /// </summary>
        internal static string RESISTOR_INFINITE {
            get {
                return ResourceManager.GetString("RESISTOR_INFINITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Trace.
        /// </summary>
        internal static string SAVE_TRACE {
            get {
                return ResourceManager.GetString("SAVE_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching values: {0}.
        /// </summary>
        internal static string SEARCHING_VALUES {
            get {
                return ResourceManager.GetString("SEARCHING_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show measure info.
        /// </summary>
        internal static string SHOW_MEASURE_INFO {
            get {
                return ResourceManager.GetString("SHOW_MEASURE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The S/N &apos;{0}&apos; does not exist in the database..
        /// </summary>
        internal static string SN_NOT_FOUND_AT_DB {
            get {
                return ResourceManager.GetString("SN_NOT_FOUND_AT_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product of the loading measurement is {0}, but the application started for product {1}. Please, fix the problem by using parameter &apos;/p:{0}&apos;..
        /// </summary>
        internal static string SQLLOAD_PRODUCT_MISMATCH {
            get {
                return ResourceManager.GetString("SQLLOAD_PRODUCT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Measurement.
        /// </summary>
        internal static string START_MEASURE {
            get {
                return ResourceManager.GetString("START_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Database.
        /// </summary>
        internal static string TEST_DATABASE {
            get {
                return ResourceManager.GetString("TEST_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string VERSION_INFO {
            get {
                return ResourceManager.GetString("VERSION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        internal static string WORKPLACE {
            get {
                return ResourceManager.GetString("WORKPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current workplace is {0}..
        /// </summary>
        internal static string WORKPLACE_INFO {
            get {
                return ResourceManager.GetString("WORKPLACE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace has not to be set..
        /// </summary>
        internal static string WORKPLACE_NOT_SET {
            get {
                return ResourceManager.GetString("WORKPLACE_NOT_SET", resourceCulture);
            }
        }
    }
}
